# fly.toml file generated for jjtactictoe on 2022-12-12T16:20:01Z

app = "amazething"
kill_signal = "SIGINT"
kill_timeout = 5
##processes = []

[env]
  PORT = "8080"
  URL = "https://amazething.fly.dev"
  CLIENT_URL = "https://chipper-kataifi-8ab766.netlify.app"
  AUTH0_AUDIENCE = "https://amaze-thing-production.com"
  AUTH0_DOMAIN = "dev-mujh303ammb4fy01.uk.auth0.com"
  AUTH0_CLIENT_ID = "lVp1cabYznnxW14RgDEUUCnGwYnD5Jdq"
  DB_URL = "mongodb+srv://admin:123@amazething.debp4ns.mongodb.net/?retryWrites=true&w=majority"
  DB_PORT = "27017"
  DB_NAME = 'amazething'

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  ##processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
